[project]
name = "ollama-tutorials"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain>=1.0.7",
    "langchain-community>=0.4.1",
    "langchain-ollama>=0.1.0",
    "pydantic>=2.12.4",
]
